package GUI;

/**
 *
 * @author Jenna Vlaar
 */
public class SeatForm extends javax.swing.JFrame {

    /**
     * Creates new form SeatForm
     */
    public SeatForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        seatFormPanel = new javax.swing.JPanel();
        seatTitle = new javax.swing.JLabel();
        seatPanel = new javax.swing.JPanel();
        screenPanel = new javax.swing.JPanel();
        screenLabel = new javax.swing.JLabel();
        seatA2 = new javax.swing.JLabel();
        seatA1 = new javax.swing.JLabel();
        seatA4 = new javax.swing.JLabel();
        seatA3 = new javax.swing.JLabel();
        seatA5 = new javax.swing.JLabel();
        seatA10 = new javax.swing.JLabel();
        seatA9 = new javax.swing.JLabel();
        seatA8 = new javax.swing.JLabel();
        seatA7 = new javax.swing.JLabel();
        seatA6 = new javax.swing.JLabel();
        seatB5 = new javax.swing.JLabel();
        seatB4 = new javax.swing.JLabel();
        seatB3 = new javax.swing.JLabel();
        seatB2 = new javax.swing.JLabel();
        seatB1 = new javax.swing.JLabel();
        seatB10 = new javax.swing.JLabel();
        seatB9 = new javax.swing.JLabel();
        seatB8 = new javax.swing.JLabel();
        seatB7 = new javax.swing.JLabel();
        seatB6 = new javax.swing.JLabel();
        seatC5 = new javax.swing.JLabel();
        seatC4 = new javax.swing.JLabel();
        seatC3 = new javax.swing.JLabel();
        seatC2 = new javax.swing.JLabel();
        seatC1 = new javax.swing.JLabel();
        seatC10 = new javax.swing.JLabel();
        seatC9 = new javax.swing.JLabel();
        seatC8 = new javax.swing.JLabel();
        seatC7 = new javax.swing.JLabel();
        seatC6 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seatFormPanel.setBackground(new java.awt.Color(41, 44, 142));

        seatTitle.setBackground(new java.awt.Color(243, 224, 52));
        seatTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 40)); // NOI18N
        seatTitle.setForeground(new java.awt.Color(243, 224, 52));
        seatTitle.setText("SELECT SEAT(S)");

        seatPanel.setBackground(new java.awt.Color(87, 79, 198));
        seatPanel.setForeground(new java.awt.Color(87, 79, 198));

        screenPanel.setBackground(new java.awt.Color(147, 155, 255));

        screenLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        screenLabel.setForeground(new java.awt.Color(69, 69, 69));
        screenLabel.setText("S C R E E N");

        javax.swing.GroupLayout screenPanelLayout = new javax.swing.GroupLayout(screenPanel);
        screenPanel.setLayout(screenPanelLayout);
        screenPanelLayout.setHorizontalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, screenPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(screenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
        );
        screenPanelLayout.setVerticalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screenLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        seatA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatA2.setText("jLabel2");

        seatA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatA1.setText("jLabel2");

        seatA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatA4.setText("jLabel2");

        seatA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatA3.setText("jLabel2");

        seatA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatA5.setText("jLabel2");

        seatA10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatA10.setText("jLabel2");

        seatA9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatA9.setText("jLabel2");

        seatA8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatA8.setText("jLabel2");

        seatA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatA7.setText("jLabel2");

        seatA6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatA6.setText("jLabel2");

        seatB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatB5.setText("jLabel2");

        seatB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatB4.setText("jLabel2");

        seatB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatB3.setText("jLabel2");

        seatB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatB2.setText("jLabel2");

        seatB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatB1.setText("jLabel2");

        seatB10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatB10.setText("jLabel2");

        seatB9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatB9.setText("jLabel2");

        seatB8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatB8.setText("jLabel2");

        seatB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatB7.setText("jLabel2");

        seatB6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatB6.setText("jLabel2");

        seatC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatC5.setText("jLabel2");

        seatC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatC4.setText("jLabel2");

        seatC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatC3.setText("jLabel2");

        seatC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatC2.setText("jLabel2");

        seatC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatC1.setText("jLabel2");

        seatC10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatC10.setText("jLabel2");

        seatC9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatC9.setText("jLabel2");

        seatC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatC8.setText("jLabel2");

        seatC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatC7.setText("jLabel2");

        seatC6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/gui/seatimages/seat.png"))); // NOI18N
        seatC6.setText("jLabel2");

        javax.swing.GroupLayout seatPanelLayout = new javax.swing.GroupLayout(seatPanel);
        seatPanel.setLayout(seatPanelLayout);
        seatPanelLayout.setHorizontalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatPanelLayout.createSequentialGroup()
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(seatPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(screenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, seatPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(seatPanelLayout.createSequentialGroup()
                                .addComponent(seatA1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seatA2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(seatA3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seatA4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seatA5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(seatA6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seatA7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(seatA8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seatA9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(seatA10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(seatPanelLayout.createSequentialGroup()
                                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(seatPanelLayout.createSequentialGroup()
                                        .addComponent(seatC1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatC2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(seatC3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatC4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatC5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seatPanelLayout.createSequentialGroup()
                                        .addComponent(seatB1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatB2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(seatB3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatB4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatB5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(seatPanelLayout.createSequentialGroup()
                                        .addComponent(seatB6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatB7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(seatB8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatB9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatB10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(seatPanelLayout.createSequentialGroup()
                                        .addComponent(seatC6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatC7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(seatC8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatC9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(seatC10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(36, 36, 36))
        );
        seatPanelLayout.setVerticalGroup(
            seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(screenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatA2)
                    .addComponent(seatA1)
                    .addComponent(seatA4)
                    .addComponent(seatA3)
                    .addComponent(seatA5)
                    .addComponent(seatA7)
                    .addComponent(seatA6)
                    .addComponent(seatA9)
                    .addComponent(seatA8)
                    .addComponent(seatA10))
                .addGap(35, 35, 35)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatB2)
                    .addComponent(seatB1)
                    .addComponent(seatB4)
                    .addComponent(seatB3)
                    .addComponent(seatB5)
                    .addComponent(seatB7)
                    .addComponent(seatB6)
                    .addComponent(seatB9)
                    .addComponent(seatB8)
                    .addComponent(seatB10))
                .addGap(40, 40, 40)
                .addGroup(seatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatC2)
                    .addComponent(seatC1)
                    .addComponent(seatC4)
                    .addComponent(seatC3)
                    .addComponent(seatC5)
                    .addComponent(seatC7)
                    .addComponent(seatC6)
                    .addComponent(seatC9)
                    .addComponent(seatC8)
                    .addComponent(seatC10))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        confirmButton.setBackground(new java.awt.Color(158, 155, 255));
        confirmButton.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seatFormPanelLayout = new javax.swing.GroupLayout(seatFormPanel);
        seatFormPanel.setLayout(seatFormPanelLayout);
        seatFormPanelLayout.setHorizontalGroup(
            seatFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatFormPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(seatFormPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seatFormPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seatTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        seatFormPanelLayout.setVerticalGroup(
            seatFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seatFormPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(seatTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(seatFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(seatFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // User pressed REGISTER
        //open register form
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel screenLabel;
    private javax.swing.JPanel screenPanel;
    private javax.swing.JLabel seatA1;
    private javax.swing.JLabel seatA10;
    private javax.swing.JLabel seatA2;
    private javax.swing.JLabel seatA3;
    private javax.swing.JLabel seatA4;
    private javax.swing.JLabel seatA5;
    private javax.swing.JLabel seatA6;
    private javax.swing.JLabel seatA7;
    private javax.swing.JLabel seatA8;
    private javax.swing.JLabel seatA9;
    private javax.swing.JLabel seatB1;
    private javax.swing.JLabel seatB10;
    private javax.swing.JLabel seatB2;
    private javax.swing.JLabel seatB3;
    private javax.swing.JLabel seatB4;
    private javax.swing.JLabel seatB5;
    private javax.swing.JLabel seatB6;
    private javax.swing.JLabel seatB7;
    private javax.swing.JLabel seatB8;
    private javax.swing.JLabel seatB9;
    private javax.swing.JLabel seatC1;
    private javax.swing.JLabel seatC10;
    private javax.swing.JLabel seatC2;
    private javax.swing.JLabel seatC3;
    private javax.swing.JLabel seatC4;
    private javax.swing.JLabel seatC5;
    private javax.swing.JLabel seatC6;
    private javax.swing.JLabel seatC7;
    private javax.swing.JLabel seatC8;
    private javax.swing.JLabel seatC9;
    private javax.swing.JPanel seatFormPanel;
    private javax.swing.JPanel seatPanel;
    private javax.swing.JLabel seatTitle;
    // End of variables declaration                   
}
